#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yellow='\033[0;33m'
no_color='\033[0m'

# To fix color issues
exec >/dev/tty 2>&1

echo -e "${yellow}TS Errors:${no_color}"
FORCE_COLOR=1 pnpm tsc --noEmit

echo -e "${yellow}Formatting, Linting, spell Checking:${no_color}"
FORCE_COLOR=1 pnpm exec lint-staged -p true
